### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Salil03** [mfornet/acmx#77] opened 2020-05-15 12:31 UTC
- Issue Type: `Performance`
- Extension Name: `acmx`
- Extension Version: `0.2.9`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

[marx24.acmx-unresponsive.cpuprofile.txt](https://github.com/mfornet/acmx/files/4634361/marx24.acmx-unresponsive.cpuprofile.txt)

Here are the activation times:

```
"activationTimes": {
		"codeLoadingTime": 621,
		"activateCallTime": 1606,
		"activateResolvedTime": 27,
}
```

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

#76 might solve it.

**Comment by mfornet** [comment] 2020-05-15 17:35
This is very helpful, didn't know about this analysis before. As you say #76 hopefully fix the problem, but maybe the issue is with most of the work performed is done in synchronously.

**Comment by Salil03** [comment] 2020-05-15 18:35
I think everything done synchronasly is the problem. We should go async wherever possible

**Comment by mfornet** [comment] 2020-05-16 22:43
I'll keep this issue open while async mechanism is not in place.

**Comment by Salil03** [comment] 2020-05-17 03:43
[CPU-20200517T034222.873Z.cpuprofile.txt](https://github.com/mfornet/acmx/files/4639609/CPU-20200517T034222.873Z.cpuprofile.txt)
Here is the profile after the bundling

**Comment by Salil03** [comment] 2022-01-18 02:58
@mfornet The actual reason for this was #132 . The checker was being compiled every time I ran the testcases. Which created an illusion of high CPU load.

**Comment by mfornet** [comment] 2022-01-20 13:13
Well, this shouldn't be a problem anymore, given we are compiling only if there are changes. closing the issue.

**Closed by mfornet** 2022-01-20 13:13 UTC

**Comment by Salil03** [comment] 2022-01-20 15:07
Only if #132  works on all os. I think only windows has `sol.exe`, all others are `sol` right?

**Comment by mfornet** [comment] 2022-01-20 15:45
> Only if #132 works on all os. I think only windows has `sol.exe`, all others are `sol` right?

Yes, this is correct. Only windows uses .exe
