### ISSUE TITLE
Problem Statement Switch

### ISSUE THREAD

**Issue by king-11** [mfornet/acmx#102] opened 2020-07-25 05:36 UTC
- If I parsed, a problem started working on it, and then when I am done with it, if I keep the file of the current solution open, I can't parse another problem only when I close the directory and file then I can parse another problem.

- It will be great to allow the parsing of a new problem even though another solution directory is open.

**Comment by mfornet** [comment] 2020-07-25 05:39
Is it possible that the issue is that you have an unsaved file and you are trying to parse problem from different competition so vscode tries to open a new file but it doesn't until you decided either to save changes or discard them?

**Comment by king-11** [comment] 2020-07-25 08:57
No, I have saved the files and am using the same platform i.e. codeforces

**Comment by king-11** [comment] 2020-07-25 12:19
@mfornet I checked and found that if I have opened the contest directory and even though I saved the files, the new problem from some other or even the same contest isn't parsed, but if I switch to some other directory or parent directory then the problems are parsed.

**Comment by king-11** [comment] 2020-07-25 12:49
@mfornet I guess it's an issue with integrated terminal open as soon as i closed terminal i can parse problems

**Comment by mfornet** [comment] 2020-07-26 01:53
@king-11 integrated terminal shouldn't be a problem at all, but somehow it is preventing your vscode from closing and opening new instance (maybe it is related to another extension you might have installed).

 I'm closing this issue for now as it looks not to be related with acmx extension.

**Closed by mfornet** 2020-07-26 01:53 UTC
