### ISSUE TITLE
.out file not reloading after re-running on WSL 2

### ISSUE THREAD

**Issue by Dogacel** [mfornet/acmx#107] opened 2020-09-01 12:24 UTC
When you run a test and out file changes, it doesn't update the current .out file on vscode for WSL 2. I must close the .out file before I run in order to see the new output. It might be a filesystem issue of vscode but still I think it is possible to force close and reopen the out file.

**Comment by mfornet** [comment] 2020-09-01 15:53
@Dogacel it happens only if you manually modify the `.out` file without saving it (i.e the editor has some changes that are not saved yet in the file).

When that happens to see new changes you should either:
1. Close and open the file to see the new changes
2. Save (unsaved) file and Run again (it generates that file again and displays it correctly)

This behavior is from how vscode handles editor views, it avoids closing unsaved files (This is not an issue but a feature). It has happened to me sometimes (mostly when I'm debugging) and I usually do 2).

Can you confirm that the issue is only with unsaved files?

**Comment by Dogacel** [comment] 2020-09-01 18:03
> @Dogacel it happens only if you manually modify the `.out` file without saving it (i.e the editor has some changes that are not saved yet in the file).
> 
> When that happens to see new changes you should either:
> 
> 1. Close and open the file to see the new changes
> 2. Save (unsaved) file and Run again (it generates that file again and displays it correctly)
> 
> This behavior is from how vscode handles editor views, it avoids closing unsaved files (This is not an issue but a feature). It has happened to me sometimes (mostly when I'm debugging) and I usually do 2).
> 
> Can you confirm that the issue is only with unsaved files?

It doesn't work either ways.
![image](https://user-images.githubusercontent.com/7023385/91889550-a5416f80-ec96-11ea-93aa-5f342f1a9206.png)

**Comment by mfornet** [comment] 2020-09-02 00:55
@Dogacel I can't reproduce this behavior locally, is it possible that you have some other extension that is taking over you editor somehow 🤔 (not sure if it is possible). Unfortunately I don't have access to testing on WSL :( but I haven't seen this on Ubuntu/Mac/Windows. However, I don't think this is related to the platform, but somehow to your setup (maybe another extension or some configuration).

**Comment by Dogacel** [comment] 2020-09-12 15:34
Can you test with any remote environment? I guess you should have the same problem with ssh connection as-well.

**Comment by mfornet** [comment] 2022-04-20 20:59
I'm closing this since I'm not able to reproduce this issue, and it is virtually impossible for me to fix it. @Dogacel (or anyone else who might have this issue) we can do pair-debugging together and try to figure out together what the problem is. In that case ping me in Telegram on the group channel.

**Closed by mfornet** 2022-04-20 20:59 UTC
Labels: bug, help wanted
